{% set name = "flake8-simplify" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: d8b38feb97fd6c5943b5d9b2ab352acea83ec036a93215c0576b9e48c6aa2dcc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - flake8 >=3.7
    - importlib_metadata >=0.9
    - astor >=0.1

test:
  commands:
    - flake8 --version | grep flake8_simplify

about:
  home: https://github.com/MartinThoma/flake8-simplify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flake8 plugin that helps you simplify your code.
  dev_url: https://github.com/MartinThoma/flake8-simplify

extra:
  recipe-maintainers:
    - dopplershift
