{% set name = "flake8-simplify" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 8ac8e0a1abbf255d5d1ff005b0ab7577ecc136510fcb7837eee4398cd262a770

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - flake8 >=3.7
    - importlib_metadata >=0.9
    - astor >=0.1

test:
  commands:
    - 'flake8 --version | grep flake8_simplify'

about:
  home: https://github.com/MartinThoma/flake8-simplify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flake8 plugin that helps you simplify your code.
  dev_url: https://github.com/MartinThoma/flake8-simplify

extra:
  recipe-maintainers:
    - dopplershift
